---
title: "R Notebook"
output: html_notebook
---

```{r}
#setup data

library(tidyverse)
library(ggplot2)
dataf = read.csv('C:/Users/Nick/Documents/GitHub/grvmodel/Python/DATA/full_race_details_ft.csv', header = TRUE, skipNul = TRUE)
dataf$race_id = as.factor(dataf$RaceId)
dataf$dog_id = as.factor(dataf$X.id_x)
dataf$box= as.factor(dataf$Box)
dataf$dist = str_replace(dataf$Distance, "m", "")
dataf$dist = as.numeric(dataf$dist)
dataf$RunTime = as.numeric(dataf$RunTime)
dataf$speed_cal = as.numeric(dataf$dist/dataf$RunTime)
dataf$split_times = as.numeric(dataf$SplitMargin)
df_tbl <- as_tibble(dataf)
df_tbl <- df_tbl%>% drop_na(RunTime, split_times)
```

```{r}
df_tbl
```




```{r}
tracks <- df_tbl %>% group_by(Track,dist) %>% summarise(mean_time=mean(RunTime) , mean_split= mean(split_times))
tracks
tracks$split_dist_estim <- (tracks$dist/tracks$mean_time)*tracks$mean_split
tracks$split_dist <- 0
tracks$track_id <- paste(substring(tracks$Track, 1,4),tracks$dist,sep = "-")
tracks
```

```{r}
rows_update(tracks, tibble)
```


```{r}
splitplot <- dataf %>% ggplot( aes(x=dist, y = split_times,color = Track)) +
  geom_point()
splitplot
```

```{r}
splitplot <- dataf %>% ggplot( aes(x=dist, y = speed_cal,color = Track)) +
  geom_point()
splitplot
```

```{r}
df_tbl$track_id <- paste(substring(df_tbl$track, 1,4),df_tbl$dist,sep = "-")
df_joined <- left_join(df_tbl, tracks, by = c("track_id"))
df_joined
```

```{r}
write.csv(tracks, 'C:/Users/Nick/Documents/GitHub/grvmodel/Python/DATA/split_dist_ft.csv')
```

