wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1651120015
    t:
      1:
      - 1
      - 55
      4: 3.9.7
      5: 0.12.14
      8:
      - 1
      - 3
      - 5
