wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1652330812
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 2
      - 16
      4: 3.9.7
      5: 0.12.14
      8:
      - 1
      - 3
      - 5
architecture:
  desc: null
  value: CNN
batch_size:
  desc: null
  value: 128
classes:
  desc: null
  value: 8
dataset:
  desc: null
  value: MNIST
epochs:
  desc: null
  value: 5
kernels:
  desc: null
  value:
  - 16
  - 32
learning_rate:
  desc: null
  value: 0.005
validation_split:
  desc: null
  value: 0.1
